### ISSUE TITLE
fetchMembers doesn't include offline members

### ISSUE THREAD

**Issue by b-hasbmans** [Merubokkusu/Discord-S.C.U.M#40] opened 2021-03-25 04:12 UTC
Hi, I ran a version of this:

https://github.com/Merubokkusu/Discord-S.C.U.M/blob/master/examples/gettingGuildMembers.py

and tacked on:

```
members_list = list(members.values())
count = collections.Counter([m['presence']['status'] for m in members_list])
print(count)
```

which returns (note: I have replaced numbers with ----):
```
Counter({'online': ----, 'idle': ----, 'dnd': ----})
```

In other words, no offline members are returned in the list.  I know you mentioned that the fetchable members is less than total members, but I didn't see any explicit mention about offline members.  Is this expected behavior/is there any way to retrieve offline members? Thanks!
_____________________
arandomnewaccount:
yea I forgot to include that in the docs thx for bringing it up.
For large guilds (```bot.gateway.session.guild('GUILD_ID').large == True```), the member list only contains the not-offline members.             
Note that some guilds are unavailable before you send the op 14 (```bot.gateway.session.guild('GUILD_ID').unavailable == True```). Those are massive guilds.      

There is a way to get offline members: op 8 (aka search guild members) can. You just need some search queries (a blank string query doesn't work unless you have perms). The more search queries you use, the more members you fetch (pretty sure it's max 100 members per search query). Gonna probs play around with it later this week and hopefully add a searchGuildMembers gateway function soon.

**Comment by Gilgames000** [comment] 2021-03-26 12:10
So basically we need to kinda brute force it by sending random queries and hopefully fetching offline members that way?
____________________________
arandomnewaccount:
For large guilds, yes. In large guilds, the member list sidebar doesn't contain offline members (you can check this by going to any large guild's member list and scrolling all the way to the bottom of it).

**Comment by Gilgames000** [comment] 2021-03-26 14:49
Yes, I know, guilds with more than 1000 members don't show offline members. I was referring to that xD
_________________________
arandomnewaccount:
closing this issue now since this is expected behavior of the fetchMembers function. I will note, however, that fetchMembers currently assumes that you only have permissions to view a text channel (and therefore, the member list on the side). There's another way to grab the entire list that requires that you have manage server perms....so, yea that'll be added after some permission utils are added into discum.

**Closed as completed** 2021-03-27 22:58 UTC
