### ISSUE TITLE
Discussion: PyArmor + PyInstaller

### ISSUE THREAD

**Issue by Gowixx** [Merubokkusu/Discord-S.C.U.M#157] opened 2021-09-01 14:29 UTC

**Comment by Gowixx** [comment] 2021-09-02 00:24
There was no issue, I tested it a long time ago, but I think it still happens. When I executed the command the code I made didn't work (For fetching members)

**Comment by ghost** [comment] 2021-09-08 13:42
Did you try compiling using [Nuitka](https://nuitka.net/doc/user-manual.html#tutorial-setup-and-build-on-windows) ? 
EDIT: 
Sorry I answered without doing much research on PyArmor, it seems like it's kinda complicated but doable

**See:** 
* https://github.com/Nuitka/NUITKA-Utilities/issues/26 
* https://github.com/dashingsoft/pyarmor/issues/174


EDIT2:
I did some testing and I managed to get it working much easier than I would've thought.

The python script is just a basic profile picture scraper
```py
import discum
token = ""
bot = discum.Client(token= token, log=True)
guild_id = '322850917248663552'
channel_id = '754536220826009670'
bot.gateway.fetchMembers(guild_id, channel_id, keep=['avatar'],startIndex=50, method='overlap',wait=1) #as shown in the docs method=overlap can fetch more member but the speed is decreased
@bot.gateway.command
def memberTest(resp):
	if bot.gateway.finishedMemberFetching(guild_id):
		lenmembersfetched = len(bot.gateway.session.guild(guild_id).members)
		print(str(lenmembersfetched)+' members fetched')
		bot.gateway.removeCommand(memberTest)
		bot.gateway.close()

bot.gateway.run()

file = open('result.txt', 'w')
for memberID in bot.gateway.session.guild(guild_id).members:
	id = str(memberID)
	temp = str(bot.gateway.session.guild(guild_id).members[memberID]['avatar'])
	print(id + '/'+ temp)
	file.write('https://cdn.discordapp.com/avatars/' + id + '/')
	file.write(temp + '.png?size=512' )
	file.write("\n")
```
I obfuscated it using this command `pyarmor obfuscate --no-cross-protection --restrict 0 main.py` 
Then I compiled it using Nuitka like that `python -m nuitka --mingw64 --follow-imports main.py`
It compiles the file successfully and the .exe can be run where you want on the PC, I also did some basic reverse engineering and it appears that the strings remain obfuscated during static analysis.

However I only tested it on 1 main python script and obviously, it won't be the same as a full source.

**Comment by Gowixx** [comment] 2021-09-09 16:50
Hey there, can you try to get it using `pyarmor pack -e "--onefile --key askf"` <- I tried that and it didn't work

**Comment by ghost** [comment] 2021-09-09 21:53
This seems a lil bit different, I will try from my side 👍

Edit: as I'm looking through pyarmor documentation pyarmor pack uses pyinstaller and I'm pretty sure that pyinstaller is the problem, since it works just fine using nuitka with pyarmor. Not trying to dict you in which way you should go in matter of obfuscation but I think Nuitka would be even more secure and viable. 

I will still do some test on my end using the args you passed me.

**Comment by FeelsBadMan1** [comment] 2021-09-27 07:42
> pyarmor obfuscate --no-cross-protection --restrict 0 main.py

I used nuitka alone then i uploaded it to virustotal and no engine detected it as malicious. I thought nuitka will obfuscate the compiled versions and send the script to 1 - 3 customers until i noticed, that it only compile to c. the dev of nuitka told me to buy commercial because this will obfuscate the script but it cost 250€ what is too much i think. i bought pyarmor earlier but compiling using pyarmor is not really secure as of virtustotal detect malware in the same script even tho no malware is included. It seems like the issue is on pyinstaller so that is why im now trying to use pyarmor & nuitka however the command you sent isnt great in obfuscating i think. im not aware what --no-cross-protection and  --restrict 0 really do also there is no --advanced 2 option on pyarmor as this only exist on pyinstaller. I think the most secure option to use is, copy the mainscript and save it to another name. then replace varnames and so on with something random. i use https://passwordsgenerator.net for random strings. you also can make functions to random names. one example would be following:
```
EZ77spShtMyPZSxT = range
BY47qxe9mPhuaZT7 = 500
kWAg3B8uA2q4w6eC = print
QvtFRCxeVMV5p9Wq = "hello world"

for _ in EZ77spShtMyPZSxT(BY47qxe9mPhuaZT7):
   kWAg3B8uA2q4w6eC(QvtFRCxeVMV5p9Wq)
```
You also can use bs64 to encode the scrings in the vars and additional you have the option to still use pyarmor and nuitka after editing your code. i think if someone try to obfuscate it he would need to uncompile the .exe then get c code with wired vars that he might not understand. then if he try to convert it back to .py he only will get this mess of vars. dong this will take lot of time and if you oush a updated version before someone is able to reverse your script i dont think he will try it for long.

**Comment by ghost** [comment] 2021-09-27 09:06
> > pyarmor obfuscate --no-cross-protection --restrict 0 main.py
> 
> I used nuitka alone then i uploaded it to virustotal and no engine detected it as malicious. I thought nuitka will obfuscate the compiled versions and send the script to 1 - 3 customers until i noticed, that it only compile to c. the dev of nuitka told me to buy commercial because this will obfuscate the script but it cost 250€ what is too much i think. i bought pyarmor earlier but compiling using pyarmor is not really secure as of virtustotal detect malware in the same script even tho no malware is included. It seems like the issue is on pyinstaller so that is why im now trying to use pyarmor & nuitka however the command you sent isnt great in obfuscating i think. im not aware what --no-cross-protection and --restrict 0 really do also there is no --advanced 2 option on pyarmor as this only exist on pyinstaller. I think the most secure option to use is, copy the mainscript and save it to another name. then replace varnames and so on with something random. i use https://passwordsgenerator.net for random strings. you also can make functions to random names. one example would be following:
> 
> ```
> EZ77spShtMyPZSxT = range
> BY47qxe9mPhuaZT7 = 500
> kWAg3B8uA2q4w6eC = print
> QvtFRCxeVMV5p9Wq = "hello world"
> 
> for _ in EZ77spShtMyPZSxT(BY47qxe9mPhuaZT7):
>    kWAg3B8uA2q4w6eC(QvtFRCxeVMV5p9Wq)
> ```
> 
> You also can use bs64 to encode the scrings in the vars and additional you have the option to still use pyarmor and nuitka after editing your code. i think if someone try to obfuscate it he would need to uncompile the .exe then get c code with wired vars that he might not understand. then if he try to convert it back to .py he only will get this mess of vars. dong this will take lot of time and if you oush a updated version before someone is able to reverse your script i dont think he will try it for long.

Yes nuitka doesn't obfuscate, that why you use pyarmor, everything is hidden during static analysis, but during heuristic analysis all the strings are deciphered (pyinstaller or nuitka), nothing is uncrackable and if you wanna make the process of reverse engineering harder I suggest you to not code in python. 
Also you can't decompile C code.

**Comment by Gowixx** [comment] 2021-09-27 18:29
Honestly, @FeelsBadMan1 you method is ok, but it's just not efficient.

**Comment by FeelsBadMan1** [comment] 2021-10-05 20:52
Hello, i tried the same thing, i added all imports manually above the obfuscated script. then i used this command to compile it to C using nuitka:
```
nuitka --warn-unusual-code --follow-imports --show-progress --assume-yes-for-downloads --standalone --plugin-enable=multiprocessing --show-modules --show-progress --mingw64 --onefile --include-package-data selenium --nofollow-import-to=importlib --no-pyi-file --experimental=use_pefile --experimental=use_pefile_recurse joiner.py
```

The final .exe file is suprisingly kinda big (75MB) and when users try to run the file they get issues similar to this:
```
Could not find "C:\Users\ADMINI~1\AppData\Local\Temp\ON4C87~1\pytransform\platforms\windows\x86_64\_pytransform.dll"
```
I looked for the dictonary but not found it so i created it, added the pytransform folder but its still the same issue....
Hopefully someone here is able to help me there

**Comment by ghost** [comment] 2021-10-05 22:53
> Hello, i tried the same thing, i added all imports manually above the obfuscated script. then i used this command to compile it to C using nuitka:
> 
> ```
> nuitka --warn-unusual-code --follow-imports --show-progress --assume-yes-for-downloads --standalone --plugin-enable=multiprocessing --show-modules --show-progress --mingw64 --onefile --include-package-data selenium --nofollow-import-to=importlib --no-pyi-file --experimental=use_pefile --experimental=use_pefile_recurse joiner.py
> ```
> 
> The final .exe file is suprisingly kinda big (75MB) and when users try to run the file they get issues similar to this:
> 
> ```
> Could not find "C:\Users\ADMINI~1\AppData\Local\Temp\ON4C87~1\pytransform\platforms\windows\x86_64\_pytransform.dll"
> ```
> 
> I looked for the dictonary but not found it so i created it, added the pytransform folder but its still the same issue.... Hopefully someone here is able to help me there

This is not nuitka repo.

**Comment by FeelsBadMan1** [comment] 2021-10-06 10:55
> > Hello, i tried the same thing, i added all imports manually above the obfuscated script. then i used this command to compile it to C using nuitka:
> > ```
> > nuitka --warn-unusual-code --follow-imports --show-progress --assume-yes-for-downloads --standalone --plugin-enable=multiprocessing --show-modules --show-progress --mingw64 --onefile --include-package-data selenium --nofollow-import-to=importlib --no-pyi-file --experimental=use_pefile --experimental=use_pefile_recurse joiner.py
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The final .exe file is suprisingly kinda big (75MB) and when users try to run the file they get issues similar to this:
> > ```
> > Could not find "C:\Users\ADMINI~1\AppData\Local\Temp\ON4C87~1\pytransform\platforms\windows\x86_64\_pytransform.dll"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I looked for the dictonary but not found it so i created it, added the pytransform folder but its still the same issue.... Hopefully someone here is able to help me there
> 
> This is not nuitka repo.

Im aware of that but the creator of Nuitka want to ern money from it by selling the commercial version. Im intressted in buying this when i have enough money so i need to wait but meanwhile i try to use pyarmor however he will defently not provide support when using pyarmor and nuitka as this is a way he dont earn money from me even tho i buy commercial after some months. currently i got 100€ and i get 50€/month so i would need to wait 3 months however my mobile data will cost 30€/month means i only get 20€ ot use each month. I asked this here as the descussions above where on the same topic "using pyarmor along with nuitka"
_________
arandomnewaccount:
closing as this has been somewhat answered

**Closed as completed** 2021-10-18 14:43 UTC

**Comment by Bebo0** [comment] 2022-05-17 23:40
I was seeing this issue too. I fixed it by manually adding the discum modules manually as hiddenimports (in the Analysis method) in the spec file:

`hiddenimports=['discum.start', 'discum.start.superproperties', 'discum.start.login', 'discum.start.other', 'discum.gateway.messages', 'discum.gateway.messages', 'discum.gateway.messages.parse'],`

Edit: the above didn't work because pysintaller couldn't recursively import all of discum's submodules. This however works perfectly:
`hiddenimports=collect_submodules("discum"),`

Hope this helps someone took me 3 days to get this to work because of silent errors
